### ISSUE TITLE
Add Cache in All Contextual API

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/uci-apis#100]
Currently, `findone` and `findallcontextual` APIs lack caching capabilities, resulting in suboptimal performance and undue strain on our server. Upon receiving a request, the APIs retrieve data from the original source, even if the requested data remains unchanged since the previous request. A caching mechanism that stores API responses and serves them directly for subsequent requests needs to be implemented here.

**Comment by geeky-abhishek** [comment]
@RyanWalker277 will update the PR.

**Comment by karntrehan** [comment]
PR raised. To be merged.

**Comment by susheelvar** [comment]
PR raised - to be verified by @chinmoy12c / @ChakshuGautam
