### ISSUE TITLE
Improve error logging in UCI-APIs

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/uci-apis#112]
The media upload api returns the following error if it is called with a duplicate form. The fix for this is just to change version in the form, but the API itself should also mention a more clear error message which can be routed to the frontend.

```
{
    "apiId": "api.form.upload",
    "path": "/admin/form/upload",
    "apiVersion": "v1",
    "msgid": "73416824-144e-4942-a97c-aae95871efd2",
    "result": {
        "status": "ERROR",
        "errorCode": "ODKUP-CP-3",
        "errorMessage": "Error in uploading Form",
        "data": {}
    },
    "startTime": "2023-06-07T07:29:41.641Z",
    "method": "POST",
    "ownerId": "8f7ee860-0163-4229-9d2a-01cef53145ba",
    "endTime": "2023-06-07T07:29:43.225Z"
}
```

**Comment by RyanWalker277** [comment]
Hey @geeky-abhishek, here is a brief about the error codes.These can be mapped to custom alerts on the frontend itself.

## Error Code: CP-0
Description: Media Files Upload Failed
Meaning: This error code indicates that the upload of media files associated with the form has failed. It suggests a problem with uploading the media files to the server.
## Error Code: CP-1
Description: Failed to Replace Media File Names
Meaning: This error code indicates that there was an error in replacing the media file names within the form file. It suggests an issue with modifying the XML or metadata of the form to reflect the uploaded media files.
## Error Code: CP-2
Description: Form Parsing Failed
Meaning: This error code indicates that the parsing of the form file failed. It suggests an issue with reading and parsing the XML or JSON structure of the form file.
## Error Code: CP-3
Description: Form Upload Failed
Meaning: This error code indicates that the upload of the form to the server failed. It suggests a problem with sending the form data or with the server-side handling of the form upload request. This generally happens when either the form id or version arent defined correctly. So, the error message for this code can include these as quick fixes.
## Error Code: CP-4
Description: Unknown Upload Error
Meaning: This error code indicates that an unknown error occurred during the form upload process. It suggests an unexpected error that is not specifically handled or categorized.
## Error Code: CP-5
Description: Form Upload Failed (Generic)
Meaning: This error code indicates a general failure during the form upload process. It is used when the specific error code or checkpoint is not available or could not be determined.

**Comment by ChakshuGautam** [comment]
Hey CP was for `CheckPoint`. We should really make these show what the actual error is even when pseudo-naming them.

**Comment by chinmoy12c** [comment]
> Hey CP was for `CheckPoint`. We should really make these show what the actual error is even when pseudo-naming them.

To be handled in #122
