### ISSUE TITLE
null description in searchbot api

### ISSUE THREAD

**Issue by geeky-abhishek** [samagra-comms/uci-apis#115]
While creating a bot we provide bot description and purpose but in bot search result in bot details these two keys were null for all bots

**Comment by geeky-abhishek** [comment]
CURL for search bot 
`curl 'http://159.65.151.114:9999/admin/bot/search?perPage=10&page=1' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'admin-token: dR67yAkMAqW5P9xk6DDJnfn6KbD4EJFVpmPEjuZMq44jJGcj65' \
  -H 'asset: bot' \
  -H 'authorization: 1WW61VevZkGwWweWNwlkvLSlbZ8Shx7Xtz6NJ6XFqTDtSuOje2jzW9A_' \
  -H 'ownerID: 8f7ee860-0163-4229-9d2a-01cef53145ba' \
  -H 'ownerOrgID: org01' \
  --compressed \
  --insecure`

**Comment by chinmoy12c** [comment]
This is tracked by #119
