### ISSUE TITLE
Update Postman Collection

### ISSUE THREAD

**Issue by geeky-abhishek** [samagra-comms/uci-apis#116]
Currently, the Postman collection is not updated with the latest/updated APIs.
A few API's that are required are: edit/delete/report/enable/disable bot

**Comment by susheelvar** [comment]
Postman collection to be shared after closing modifications by @chinmoy12c

**Comment by chinmoy12c** [comment]
@chinmoy12c to share the collection today.

**Comment by geeky-abhishek** [comment]
need email verification by @karntrehan

**Comment by geeky-abhishek** [comment]
https://making-impact-at-scale.postman.co/workspace/Team-Workspace~0829531a-4751-4222-858f-d76774ea3c96/collection/19777315-144f9028-3e04-4ed9-8442-dcf750588e78?action=share&creator=19777315
