### ISSUE TITLE
Update Edit Api

### ISSUE THREAD

**Issue by geeky-abhishek** [samagra-comms/uci-apis#136]
Currently, Edit Api completely overrides the original object which should be updated to upsert query to update only the passed values.

**Comment by chinmoy12c** [comment]
What will be the implication of this on the transaction layer? Since bots are cached on the transaction layer, when an update in a bot occurs the cache will need to be validated both on UCI-API and the transaction layer services, or it will introduce inconsistencies.

**Comment by geeky-abhishek** [comment]
The transaction layer also needs to provide an endpoint for invalidating the cache.

**Comment by geeky-abhishek** [comment]
PR to be raised by @chinmoy12c today

**Comment by karntrehan** [comment]
Merged to develop. To be deployed.
