### ISSUE TITLE
Create flow diagram of message flow in UCI on Draw.io

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#150]
Create a diagram of the flow of notifications within the UCI system for benchmarking and analysis.

**Comment by geeky-abhishek** [comment]
@chinmoy12c will be done by today

**Comment by chinmoy12c** [comment]
Here is the detailed flow of:

- allContextual
- conversation history
- odk bot conversation

https://drive.google.com/file/d/1pq3ZdEic8ZvPuJlM50EWpGjZ1OQz1ZGY/view?usp=sharing

**Comment by aakashyadav-kgp** [comment]
@chinmoy12c to attach benchmark of each process. 
and document the Action items that come out of this exercise.

Add the diagram to the documentation @chinmoy12c

**Comment by chinmoy12c** [comment]
Issues which were identified during the analysis:

- [ ] https://github.com/samagra-comms/inbound/issues/74
- [ ] https://github.com/samagra-comms/inbound/issues/75

**Comment by karntrehan** [comment]
Diagrams being reviewed by @ChakshuGautam
