### ISSUE TITLE
Handling of expired bots

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#163]
We need to take a call on how the expired bots need to be handled on the user's end.

**Comment by aakashyadav-kgp** [comment]
On the bot list screen. Let's show a marker that says expired. On clicking user can see the chat he/she has had in the past and when the user types and sends anything. We respond that "यह फॉर्म समाप्त हो गया है !" 
@chinmoy12c

**Comment by aakashyadav-kgp** [comment]
Disable input if the bot is expired. Show Content in the input field. 
Handling expiry on UCI web channel itself.

**Comment by RyanWalker277** [comment]
Placement of content to be changed in input field. Updated build to be shared by @geeky-abhishek
