### ISSUE TITLE
Debug load on system when triggering notifications

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#173]
When we are triggering notifications for 1L users, the system is going under a lot of load. This is degrading performance for users. We should debug the cause of load and reduce it. 

Alt from @aakashyadav-kgp: When we send notification the chat bot doesn't respond due to high load on server. We want to optimise this as we expect users to respond as we send notification. Given the bot doesn't respond, user are not able to interact appropriately with the bot.

**Comment by chinmoy12c** [comment]
The load issue on the system has been resolved with the separation of Kafka topics. Closing this issue now.
