### ISSUE TITLE
Add order by parameter in search API

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#174]
The search API needs to provide an `orderBy` field in the history API so that it's easier for the frontend to render the data.

**Comment by aakashyadav-kgp** [comment]
@geeky-abhishek to test this and close.

**Comment by geeky-abhishek** [comment]
[PR#174](https://github.com/samagra-comms/uci-apis/pull/200) is raised

**Comment by karntrehan** [comment]
Staging deployment to done.
