### ISSUE TITLE
[Android] Debugging why PN not sent to all users

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#175]
Description: From the recent bot triggering exercise we have observed that ~40% of all users, to whom we successfully send notification, receive notification. The drop is quite massive and we want to know ways of improving it.

**Comment by karntrehan** [comment]
Google mentions that we should target users with token less than 1 month old. Source: https://firebase.google.com/docs/cloud-messaging/manage-tokens

We currently have 1,33,407 tokens in the system.
Created this sheet with the mentor token age with help from @choxx : https://docs.google.com/spreadsheets/d/1-PS0FNf31l61q9M2Uvh_jrVc9oiJGZXFk2wS903owLU/edit?usp=sharing

Summary: 

![Image](https://github.com/samagra-comms/uci-apis/assets/5885669/9cfe118f-b08b-4e41-80d8-d657e43a3f7a)

We can target 88,289 mentors with token less than a month old. Which is ~66%

Reach: 

Currently we are reaching 42K users which is ~48% users of 88,289 reachable users. 

Next steps: 
1. Look at users who could be offline. 
2. Users with notifications turned off. 
3. Users who have uninstalled the app.

**Comment by aakashyadav-kgp** [comment]
Top of funnel. i.e., total target group is almost 95% of cohort we want to send notification to. For now we are focusing on getting more accurate notification received data because we feel there some data leak happening on posthog. Therefore we are not getting the exact data there. Exploring firebase for the same.

**Comment by karntrehan** [comment]
Blocked on lack of bandwidth

**Comment by aakashyadav-kgp** [comment]
@karntrehan I did one round of debugging. Found that more than 1.5L token are < 30 days. Theoritically we should be able to send notification to these users. 

![Image](https://github.com/samagra-comms/uci-apis/assets/111346170/b7b334f7-94e8-415e-8fb3-7f615a079f24)

**Comment by karntrehan** [comment]
- [ ]  Add botId to the analytics object of notifications - https://firebase.google.com/docs/cloud-messaging/understand-delivery?platform=android#adding-analytics-labels-to-messages
- [ ] Check time_to_live flag on the messages
- [x] Periodic FCM Token updates on Android

**Comment by pankajjangid05** [comment]
Add botId to the analytics object of notifications is done



![Image](https://github.com/samagra-comms/uci-apis/assets/103931276/ccf3b24f-a6c0-49ce-9cac-7ea5501cb9d1)

**Comment by geeky-abhishek** [comment]
Need schema approval from @chinmoy12c .

**Comment by pankajjangid05** [comment]
Delivery report new database was created and related changes are done. PR is created and waiting for Chinmoy's approval.

https://github.com/samagra-comms/inbound/pull/94

**Comment by geeky-abhishek** [comment]
@pankajjangid05 to deploy it today on staging

**Comment by karntrehan** [comment]
Production deployment broke redis cache. To be hotfixed and deployed today.
Numbers to be compared for new bots triggered from tomorrow.

**Comment by pankajjangid05** [comment]
Deployment done Production is working fine.

**Comment by karntrehan** [comment]
Fixes released in v1.7.3 of NL.
