### ISSUE TITLE
Invalidate cache on transaction layer on bot update

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#202]
Transaction layer bot cache needs to be invalidated on bot update so that there is no inconsistent data on the transaction layer after an update occurs.

**Comment by chinmoy12c** [comment]
@pankajjangid05 please attach the curl for invalidating the cache on transaction layer.

**Comment by pankajjangid05** [comment]
API for remove caffeine cache from transaction layer  : 
```
curl --location --request DELETE 'http://159.65.151.114:9080/cache/caffeine/removeAll' \
--header 'Content-Type: application/json'
```

**Comment by chinmoy12c** [comment]
PR has been raised.
