### ISSUE TITLE
Setup monitoring for bot health

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#211]
Set up monitoring of bot health on grafana same as other health services.

**Comment by RyanWalker277** [comment]
Will share the final update by today @geeky-abhishek

**Comment by karntrehan** [comment]
Pr feedback to be worked on

**Comment by geeky-abhishek** [comment]
@geeky-abhishek to check the comments on PR

**Comment by geeky-abhishek** [comment]
@chinmoy12c new PR link-https://github.com/samagra-comms/uci-apis/pull/218

**Comment by chinmoy12c** [comment]
Merged to develop.
