### ISSUE TITLE
Provide endpoints for deletion of bots.

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#223]
Two separate endpoints are required:

- [x] Delete bots using a list of bot IDs.
- [x] Delete bots within a start and end date.

**Comment by chinmoy12c** [comment]
Api dev is done, need to add unit tests.

**Comment by aakashyadav-kgp** [comment]
PR raised. To be reviewed by chakshu.

**Comment by chinmoy12c** [comment]
To be merged today.
