### ISSUE TITLE
[DevOps] Add monitoring to UCI backend services

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#53]
We need to add monitoring to all services of UCI. Currently deployments are becoming black boxes.

**Comment by karntrehan** [comment]
Depends on https://github.com/samagra-comms/uci-apis/issues/54 to be merged.

**Comment by karntrehan** [comment]
@tushar5526 to transfer ownership to @choxx

**Comment by tushar5526** [comment]
@choxx 
I have added the monitoring for Host and Container services for UCI. Please configure alerts for Containers (if there are any like in other projects) and review the alerts for `Host`

Apart from this, services in UCI need to be monitored.

![image](https://user-images.githubusercontent.com/30565750/232412225-36e9872c-4a35-44e0-bf47-799dcce54323.png)


The following services have a `/health` endpoint
- broadcast-transformer
- inbound
- uci_orchestrator
- uci_outbound
- uci_transformer
- uci_uci-API-service
- uci_uci-transport-socket

**Comment by karntrehan** [comment]
Plan is to pick monitoring on new prod server.

**Comment by choxx** [comment]
All the above-mentioned services have been added to the monitoring. However, the UCI API service doesn't seem to have any health check endpoint at: `/health` (so currently the health checks are failing).

![Image](https://user-images.githubusercontent.com/11666456/233918835-240495aa-60b5-499b-ae79-a091a74487c5.png)

**Comment by karntrehan** [comment]
@chinmoy12c working on health checks in UCI APIs.

**Comment by chinmoy12c** [comment]
PR waiting for review. @ChakshuGautam

**Comment by susheelvar** [comment]
Review awaited.

**Comment by susheelvar** [comment]
@pankajjangid05 to check if PR reviewed. If not to update @karntrehan

**Comment by chinmoy12c** [comment]
PR is still awaiting review. Health endpoints are live and working on the transaction layer, but still not merged in UCI-API.
This is the PR: https://github.com/samagra-comms/uci-apis/pull/66

cc @karntrehan

**Comment by chinmoy12c** [comment]
@choxx to update on the uci-api monitoring.

**Comment by susheelvar** [comment]
@choxx to integrate authentication request handling to Health Check [repository](https://github.com/Samagra-Development/health-check-json-timeseries-metrics)

**Comment by choxx** [comment]
> @choxx to integrate authentication request handling to Health Check [repository](https://github.com/Samagra-Development/health-check-json-timeseries-metrics)

Added support for various request methods & authorization headers. Added monitoring for UCI API Service; set up alerts. Please verify.
![image](https://github.com/samagra-comms/uci-apis/assets/11666456/48513355-7fef-4c21-b5db-bb135732718d)
