### ISSUE TITLE
Extend /health endpoints to make them async and detailed

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#54]
Current /health endpoints of services are not very intuitive. They are also synchronous leading to blockages of 4 seconds on each call to /health.

 We should make them async and also check internal working like kafka giving 500s.

**Comment by karntrehan** [comment]
@chinmoy12c to document the schema here.

**Comment by karntrehan** [comment]
Pr raised. @pankajjangid05 to review.

**Comment by chinmoy12c** [comment]
The response JSON schema needs to be changed. @tushar5526 please add the required schema.

**Comment by chinmoy12c** [comment]
These are the PRs @pankajjangid05 

https://github.com/samagra-comms/transformer/pull/63
https://github.com/samagra-comms/orchestrator/pull/32
https://github.com/samagra-comms/inbound/pull/40
https://github.com/samagra-comms/outbound/pull/26

**Comment by pankajjangid05** [comment]
@chinmoy12c These PRs are merged.
