### ISSUE TITLE
Media upload API

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#55]
Logic change to enable media file upload integration to XML 

We will need to check the impact of this on the Android image downloading mechanism.

**Comment by karntrehan** [comment]
Adding files to ODK would require the following changes: 
1. Add media when creating ODK form
2. Save media to odk aggregate
3. Pass url of uploaded media to uci 
4. UCI sends media url to FE to support downloading 


A better approach would be to power this through minio itself. Where the media is uploaded and the URL is added to ODK form. We can check if we can automate the minio url updation in ODK. 

cc @chinmoy12c @ChakshuGautam

**Comment by karntrehan** [comment]
To be reviewed by @pankajjangid05 , @surabhi-mahawar @ChakshuGautam

**Comment by karntrehan** [comment]
@karntrehan to let @chinmoy12c know tags used for image handling in ODK - UCI

**Comment by karntrehan** [comment]
The generated XML is of the following format: 

For image:
```xml
<text id="/data/tunnel/display_cdn_image:label">
    <value>013a2da7-9329-4312-8e50-9fc27b709307.jpeg</value>
    <value form="image">jr://images/yes</value>
</text>
```

Here value xxx.jpg is the ID returned from minio upload.

For Video:
```xml
<text id="/data/tunnel/display_cdn_video:label">
    <value>d643f27f-f62f-4d0d-b985-abcaa927c6e8.mp4</value>
    <value form="image">jr://images/yes</value>
</text>
```

For Document / Pdf: 
```xml
<text id="/data/tunnel/display_cdn_document:label">
    <value>1096555e-ac72-4139-a977-1602d7d58713.pdf</value>
    <value form="image">jr://images/yes</value>
</text>
```

**Comment by chinmoy12c** [comment]
PR updated, waiting for review.

**Comment by chinmoy12c** [comment]
Sharing the updated curl here:

```
curl --location 'http://[UCI_API_HOST]/admin/form/upload' \
--header 'admin-token: [ADMIN_TOKEN]' \
--form 'form=@"/home/chinmoy/Downloads/testing_form.xml"' \
--form 'mediaFiles=@"/home/chinmoy/Downloads/bot.png"' \
--form 'mediaFiles=@"/home/chinmoy/Downloads/bot_circle.png"'

```

**Comment by geeky-abhishek** [comment]
@chinmoy12c we should connect to discuss this for the frontend changes

**Comment by geeky-abhishek** [comment]
@pankajjangid05 will check for 505 error
