### ISSUE TITLE
Token Expired

### ISSUE THREAD

**Issue by tushar5526** [samagra-comms/uci-apis#61]
https://github.com/samagra-comms/uci-apis/blob/v2/v2/uci/.npmrc#L1

This token has expired and public users won't be able to install the project using docker-deploy.

**Comment by ChakshuGautam** [comment]
Hey this was my personal token. Can we create an samagra-comms token and start using that?

**Comment by tushar5526** [comment]
@karntrehan can you help here? We can leverage the common engineering mail. @ChakshuGautam what are the steps to create one or any other doc?

Can't we make this dependency public?

**Comment by tushar5526** [comment]
https://github.com/samagra-comms/uci-apis/blob/v2/v2/uci/.npmrc - this token

**Comment by karntrehan** [comment]
Created a token for Samagra Comms. Shared over personal message.
