### ISSUE TITLE
`Vaults` dependency removal

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/uci-apis#85]
The dependency on https://github.com/mittwald/vaulTS/pkgs/npm/vaults needs to be removed. Currently we need a github token to install this. Expected outcome would be a PR removing this blocker and implementing direct installation

**Comment by chinmoy12c** [comment]
@pankajjangid05  to connect with @RyanWalker277 to debug this further.

**Comment by chinmoy12c** [comment]
@RyanWalker277 to raise a PR for this today.

**Comment by RyanWalker277** [comment]
The [new hasicrop client](https://www.npmjs.com/package/node-vault-client#VaultClient.clear) dosent have a delete method to delete a secret from vault. The following endpoints will become unusable after the migration:

DELETE /admin/secret/{Secret_name} - Delete a secret
DELETE /admin/secret/{Secret_name} - Delete all secrets

These endpoints aren't being used anywhere in the API layer internally, but will have to check if transaction layer uses these at any place. Would need to take a call on what needs to be done here.
