### ISSUE TITLE
Pass auth token to segment url

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/uci-apis#88]
Currently, segment URLs are unprotected and do not require any kind of authentication. The segment URLs will be guarded with auth token and uci-api needs to forward that token fetching data from the segment URLs.

**Comment by karntrehan** [comment]
Currently headers being passed as an array. We should move to header object array

**Comment by susheelvar** [comment]
@RyanWalker277 to pick after discussing with @geeky-abhishek 

Admin panel sends auth token to UCI APIs; to be sent to NL App.

**Comment by RyanWalker277** [comment]
To be picked up by @chinmoy12c

**Comment by susheelvar** [comment]
@ChakshuGautam please review raised PR.

**Comment by susheelvar** [comment]
PR merged.
