### ISSUE TITLE
Bulk Data Insertion in Fusion Auth

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/uci-apis#99]
The `addbottoregistry` and `adddevicetoregistry` APIs in Fusion Auth currently process data individually, resulting in slow processing times for large data sets exceeding 80,000 entries. To improve efficiency and accommodate bulk data queries, it is necessary to modify these APIs to support batch processing.

**Comment by geeky-abhishek** [comment]
@RyanWalker277 is working on it. Currently don't have a bulk upload function.So, will try batch request

**Comment by susheelvar** [comment]
@RyanWalker277 to close addition of tests today.

**Comment by susheelvar** [comment]
PR raised. To be reviewed by @chinmoy12c on 14 June.

**Comment by susheelvar** [comment]
Reviewed by @chinmoy12c ; changed to be made by @RyanWalker277.

**Comment by karntrehan** [comment]
Test case being fixed.

**Comment by geeky-abhishek** [comment]
@chinmoy12c to review the changes
